### ISSUE TITLE
Error with php7

### ISSUE THREAD

**Issue by dmitrijsmihailovs** [briedis/api-builder#4]
Hi, i'm getting this error using php7

`Cannot use Briedis\ApiBuilder\Items\Float as Float because 'Float' is a special class name`

**Comment by briedis** [comment]
Good catch! :) Fixed it and made a new release v1.1.2.

**Comment by dmitrijsmihailovs** [comment]
Same with String, i'm guessing it's same with other classes too.

`Cannot use Briedis\ApiBuilder\Items\String as String because 'String' is a special class name`

**Comment by briedis** [comment]
Ok, I suffixed all the classes with Item. No more conflicts, hopefully :)

**Comment by dmitrijsmihailovs** [comment]
Fixed :)
